"""Object storage protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageProtocol(Protocol):
    """Contract for object storage adapters."""

    async def upload(self, key: str, data: bytes, content_type: str) -> None: ...

    async def upload_file(self, key: str, file_path: str, content_type: str) -> None: ...

    async def download(self, key: str) -> bytes: ...

    async def stream_range(self, key: str, start: int | None, end: int | None) -> tuple[bytes, str, int]: ...

    async def delete_prefix(self, prefix: str) -> None: ...

    async def generate_presigned_get_url(self, key: str, expires_in: int) -> str: ...

    async def generate_presigned_put_url(self, key: str, expires_in: int, content_type: str) -> str: ...

    async def exists(self, key: str) -> bool: ...
